### PR TITLE
Enhancement/error fmt

### PR DESCRIPTION
**Pull request by lthibault**
⚠️ Recommend merging #15 before reviewing this PR (current PR is branch of #15) ⚠️ 

The current PR refactors error formatting to be more idiomatic, leveraging `fmt.Formatter`.

Along the way, I have removed all position-tracking fields from `core.Error`, which are currently unused.  I have an idea in mind that that would allow us to print erroneous forms with useful debug information and will get to it ASAP.

⏱️ Estimated review time:  5 minutes
✅ Merge when ready

### CODE REVIEW

**Comment by spy16** [comment]
There seems to be some formatting issues right now ? 🤔  I just ran `go run examples/simple/main.go`

```
>> ]
File "<REPL>" line 1, column 1
ReaderError: ReaderError: unmatched delimiter ']'
>> j
&fmt.wrapError{msg:"not found: j", err:(*errors.errorString)(0xc000110230)}
>> )
File "<REPL>" line 1, column 1
ReaderError: ReaderError: unmatched delimiter ')'
>> '
  | "
  | '
  | '
  | "
"\n'\n'\n"
>> ls
&fmt.wrapError{msg:"not found: ls", err:(*errors.errorString)(0xc000110230)}
```

**Comment by lthibault** [comment]
Ok should be fixed.  `repl.Renderer` now formats output using `%#s`.  As far as I know, the `#` modifier isn't routinely used with `%s`, so I think this is probably a good convention to use within the project.  The way I see it:

- `%s` (or `%v`):  _just print the error message_
- `%#s`:  _pretty-print the error message_

**Comment by spy16** [comment]
I really like the new format for reader errors 🙂  And, yes, I think `%#s` works.. That way `%+v` and `%#v` remain useful as well for debugging etc.

**Comment by spy16** [comment]
Oh looks like this issue still persists:

```
>> ]
File "<REPL>" line 1, column 1
ReaderError: ReaderError: unmatched delimiter ']'
```

`ReaderError` is repeating twice.

**Comment by lthibault** [comment]
>I really like the new format for reader errors 🙂

Awesome -- glad to hear it!  Having nice error messages has been on my mind practically since day 1, and I feel like we're finally getting there 😄 


>Oh looks like this issue still persists:

Oh!  Wow... I somehow didn't even notice that repetition.  I'll fix this up today.

**Comment by lthibault** [comment]
Ok, actually it was a quick fix.  Should be good now.

Let me know if there are any other issues or if you have any other comments/suggestions, else merge at your discretion 🙂

**Pull request merged**
